#pragma once

#define GAMEOBJECTTYPE_TILE "Tile"

#define GAMEOBJECTTYPE_COMPANY_INFO "CompanyInfo"
#define GAMEOBJECTTYPE_COMPANY "Company"

#define GAMEOBJECTTYPE_REGIONS "Regions"

#define GAMEOBJECTID_WORLD 2
#define GAMEOBJECTID_COMPANIES 1
